[package]
name = "fourier-viewer"
description = "View spectra!"
version = "0.0.0"
authors = ["kbone <kbonehobby@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
